export const alignmentMappingValues = {
  "text-left": "left",
  "text-center": "center",
  "text-right": "right",
  "text-justify": "justify",
  "flex": "flex",
  "inline-flex": "inline-flex",
  "flex-row": "row",
  "flex-row-reverse": "row-reverse",
  "flex-col": "column",
  "flex-col-reverse": "column-reverse",
  "items-start": "flex-start",
  "items-center": "center",
  "items-end": "flex-end",
  "items-stretch": "stretch",
  "justify-start": "flex-start",
  "justify-center": "center",
  "justify-end": "flex-end",
  "justify-between": "space-between",
  "justify-around": "space-around",
  "justify-evenly": "space-evenly",
};
